### ISSUE TITLE
No cars etc. in Simulation

### ISSUE THREAD

**Issue by khan101101** [sidewalklabs/sumo-web3d#35]
Hi,
I am able to run the simulation but I don't any movement in there, just the scenarios can be loaded. Any help will be highly appreciated. 

Thank you.
Regards
Nasim

**Comment by mlclemente** [comment]
I am encountering the same problem. I downloaded the tar.gz file, corrected the two things in setup.py as suggested in issue #32, and replaced trafficlights module with its new name trafficlight (see issue #31), I corrected config file (run.sumo.cfg) of default bologna-acosta scenario, where list of input files were not comma separated. Now the scenario can be loaded, the simulation seems to run but without showing vehicles in it. Now I don't know how to go on because there are no errors in stdout nor in log file.

**Comment by avalon-mcy** [comment]
The server.py has a problem in simulate_next_step(): traci.simulation.getSubscriptionResults(), this function return an empty result.
I just use traci.vehicle.getIDList() as ids and vehicles showing in it

**Comment by avalon-mcy** [comment]
The server.py has a problem in simulate_next_step(): traci.simulation.getSubscriptionResults(), this function return an empty result.
I just use traci.vehicle.getIDList() as ids and vehicles showing in it

**Comment by Laudarisd** [comment]
@avalon-mcy I am still not able to see cars or any other vehicles.
Any idea to get rid of this issu?

**Comment by apostolosvou** [comment]
@avalon-mcy i tried this but I'm still not able to see cars in the simulation. Could you explain this change further or suggest me any other solution?
Thank you in advance
